### ISSUE TITLE
Improve chat style

### ISSUE THREAD

**Issue by MaurerKrisztian** [MaurerKrisztian/SimpleChatApi#1]
- The chat should be always full screen and responsive
- Better colors

**Comment by ARJITMALIK** [comment]
Morning @MaurerKrisztian , I am  interested to work on the issue , can I continue working on it 😃😃

**Comment by MaurerKrisztian** [comment]
Hi. Thanks for your contribution. I merged the pull request. But the result seems like missing something. The chat message color is same with the background color, and not always full screen (width and height) . Please check it.

**Comment by ARJITMALIK** [comment]
Sure, I will look into that , maybe its beacuase of bubbling in javascript

**Comment by MaurerKrisztian** [comment]
I fixed the text color issue, and the date format. btw I like the neon style, good job 😃

**Comment by MaurerKrisztian** [comment]
Maybe the scroll bar can also be neon style. 🤔
